<h2>About</h2>

<p>
    Convert <a href="http://wordpress.org/plugins/about/">WordPress Plugin Readme Files</a> to
    <a href="http://github.github.com/github-flavored-markdown/">GitHub Flavored Markdown</a> online!
</p>

<h3>Libraries</h3>

<ul>
    <li><b><a href="https://github.com/benbalter/WP-Readme-to-Github-Markdown">WP Readme to Github Markdown</a></b>
    <li><b><a href="https://github.com/sunchaserinfo/wp2md">WP2MD</a></b>, a CLI tool and a composer installable package
        based on <b>WP Readme to Github Markdown</b>
    <li><b><a href="http://parsedown.org">Parsedown</a></b>, a PHP Markdown parser
</ul>
