<?php
/**
 * @author Christian Archer
 * @copyright 2014, Christian Archer
 * @license AGPL-3.0
 */
?>

<h2>About</h2>

<p>
    Convert <a href="http://wordpress.org/plugins/about/">WordPress Plugin Readme Files</a> to
    <a href="http://github.github.com/github-flavored-markdown/">GitHub Flavored Markdown</a> online!
</p>

<h3>Libraries</h3>

<ul>
    <li><b><a href="https://github.com/wpreadme2markdown/wp-readme-to-markdown">WP Readme to Github Flavored Markdown</a></b>
    <li><b><a href="http://parsedown.org">Parsedown</a></b>, a PHP Markdown parser
</ul>
