<?php
/**
 * @author Christian Archer
 * @copyright 2014, Christian Archer
 * @license AGPL-3.0
 *
 * @var string $markdown
 * @var string $markdown_html
 */
?>

<ul class="nav nav-tabs">
    <li class="nav-item"><button id="source-tab"  data-bs-toggle="tab" data-bs-target="#source"  class="nav-link active">Source</button></li>
    <li class="nav-item"><button id="preview-tab" data-bs-toggle="tab" data-bs-target="#preview" class="nav-link">Preview</button></li>
</ul>

<div class="tab-content">

    <div class="tab-pane active" id="source">
        <form action="/download" method="post">
            <div class="mb-3">
                <label for="markdown">&nbsp;</label>
                <textarea id="markdown" name="markdown" class="form-control" rows="20" readonly><?= htmlentities($markdown) ?></textarea>
            </div>
            <input type="submit" value="Download" class="btn btn-primary">
            <a href="/" class="btn btn-default">Back</a>
        </form>
    </div>
    <div class="tab-pane" id="preview"><?= $markdown_html ?></div>
</div>

